#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Courses', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # hello again!

  I am Rachel, a rising junior studying at the University of California, Berkeley.
  Currently, I am pursuing a simultaneous degree in Data Science and Environmental Science.    
  &nbsp; 
  &nbsp;                                 

  This website was build with the foundations of Paul LeN's jekyll theme. Full credit to him for a majority of the skeleton which can be found here:
  [check out the demo](lenpaul.github.io/portfolio-jekyll-theme/), and [fork the repository](https://github.com/LeNPaul/portfolio-jekyll-theme/fork), to get started.

contact: >
  # Contact

  You may contact me [through my email](mailto:rachelngjiemin@gmail.com) or drop me a [Linkedin Message](https://www.linkedin.com/in/rachel-ngjiemin/) if you have any questions or would like to stay connected!

intro: > 
  # hello! I am Rachel and thanks for dropping in. Head over to the about section to find out more about me. Alternatively, explore projects that I've been involved in below 

#-------------------------------
# Work Section

projects:
- {name: 'people and places!', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'course projects', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'other projects', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'volunteer work', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'designs', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'github', link: 'https://github.com/rachelngjiemin'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/rachel-ngjiemin/'}
- {icon: 'envelope', link: 'mailto:rachelngjiemin@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
